language: node_js
node_js:
- node
deploy:
  provider: npm
  email: jdhamlik@gmail.com
  api_key:
    secure: bliC1P8VSTXnLSTd0G7591gPwUKg2vh7Dr0SKuLhj5im0hDUCC4FFXJBJWyapJ7t/zCFmYSi8FIZpuSHhIZ9n9q93Zvu9N38NQTrV2lgUe6mQ6q5SQyteOPwYY5F+F6vHfY6bDY1wTML+d5eccyfZL45P1iOHEpXzzhm+hQlokZMuxS2N8kUNVq6Xo8Nxv3rzjzbcuqB7EKIyLGPopuQJtCkhaI9nlOlyjdMAHJ7W3zMuTaO+QctUCZjr5SHMfZ4FpEjcjPROSZBA6yO+pulZkcFbFqite+Cfne3uVP1vn8FipC0KMlC/4zxtHyB6lUCo8DTAHLmVBk8TZO7utkF/HVYseHbHfdQtYfzpz1wLKL3cNpvKMpi4CqSH48kun7CNGIAWco/RWjCAh+M5/fJMPnkVDterdYLJ9pTAgdEor5KDEbkySDFOE1PLEYAlzX6wImMoFAlVR205GzweUwR9KRdssDG7FnQ2JIfC4OZq4jk+uV7sj92yB+yZBxMLCXpagEpF4yoqYB7/qy9il/SuLhkDDVh6hG2I707/KjurHW6/23hbvru1ThIYluwkzsB8FDbkUHHllTeoQFIXBqdXazH/fDGnoexJ6UY9nbgZ6Zk8WsOzMhcvvXTNpur04a1YLP5TMxqC5JDRNDG2wp4AtMGwlxqUzgUxaRgVdsCzi8=
